### ISSUE TITLE
Aurora Factory Deployment

### ISSUE THREAD

**Issue by skellet0r** [curvefi/curve-docs#68]
### Core
* Factory: `0x51043fC6789fE61E1503b56772160aE633D7D514`

### Metapools 
* MetaUSDBasic ``
* MetaUSDBalances ``
* MedaUSDDepositZap ``

### Plain (2 coins)
* Plain2Basic `0x55c0B840016eBEFa0d01429A4256c34c581249Cf`
* Plain2Balances `0x176a440127421176C04890F871459D664e08E83A`
* Plain2ETH `0x53116a7E7e6D88c113F8b1F94F72b94259C5f7eF`
* Plain2Optimized `0xaa3729124550848cEecac433498C8e70fb6fB4CB`

### Plain (3 coins)
* Plain3Basic `0x917299485bD0B35982c19D4eE82D2c51372aF107`
* Plain3Balances `0x61cCD40aF54A6430B388a5fa2e607baDf2F38913`
* Plain3ETH `0x0dc66d568768747FE38c979EbF87E89960AF326e`
* Plain3Optimized `0x4632a182292eE910D5aEd08942904389AF9CF2Ac`

### Plain (4 coins)
* Plain4Basic `0xCd98A7c5466831A8b657230BAA89C0ebB492280B`
* Plain4Balances `0xA2eD59e795A559Fc5f1eca83Ab6e781eDf22c45D`
* Plain4ETH `0x1ba8fcCFaB2A5aCc14038bd2a164c01Ee0656672`
* Plain4Optimized `0xE26f0B8Ca6540BC9d836C9CD10cb4b23F7143E2e`

**Comment by skellet0r** [comment]
Brownie Network Config

```yaml
live:
  - name: Aurora (Near)
    networks:
      - name: Mainnet
        chainid: 1313161554
        id: aurora-main
        host: https://mainnet.aurora.dev/
        explorer: https://api.aurorascan.dev/api
        multicall2: "0xace58a26b8Db90498eF0330fDC9C2655db0C45E2"
```
