### ISSUE TITLE
Kava Factory Deployment

### ISSUE THREAD

**Issue by skellet0r** [curvefi/curve-docs#69]
### Core
* Factory: `0x40bc62805471eF53DdD5C5cF99ed3d9e5aa81b48`

### Metapools 
* MetaUSDBasic ``
* MetaUSDBalances ``
* MedaUSDDepositZap ``

### Plain (2 coins)
* Plain2Basic `0x2632679f5CA396a1bd2647092d9dBf7eC5d7B263`
* Plain2Balances `0x12f196251EfcaCA0fd73D5b58132B16760ba96A8`
* Plain2ETH `0xafdAB4F8F6E6992B16e3906295FbA390aAB59CA5`
* Plain2Optimized `0x50D7A3e0d5350d52e9E08a1b58EeFD1dB8759d7D`

### Plain (3 coins)
* Plain3Basic `0xc8913D486a42459e6B34db33F0C660FCa61306b9`
* Plain3Balances `0xC5eC776A55eA062FA3173C6C76703E9c9fA91C47`
* Plain3ETH `0xED2c5F2C4CAb6E82630d5615EA15Dd47d8B29983`
* Plain3Optimized `0xE7d5293c01685A414dDDE527eB5eFfbF92b52648`

### Plain (4 coins)
* Plain4Basic `0x77016d2dE65DE15a3C36bEBBDdc90804f670d2d0`
* Plain4Balances `0xd59C875DcCb6cDCb3a75B91b58A363b5e4B0ca9A`
* Plain4ETH `0x6378dD741B24BD884f3590d7bc7555FdB2f5b003`
* Plain4Optimized `0x509495DFEEc3a53aCb2F60669985d868131Ad9a5`

https://gist.github.com/skellet0r/dce1cd4d3e4a5b72179521f750f911f2

**Comment by skellet0r** [comment]
Brownie Network Config

```yaml
live:
  - name: Kava
    networks:
      - name: Mainnet
        chainid: 2222
        id: kava-main
        host: https://evm.kava.io
        explorer: https://explorer.kava.io
        multicall2: "0x30A62aA52Fa099C4B227869EB6aeaDEda054d121"
```
